
var words = ['Le Sob',
'The Perching Derrière ',
'Oaty Bottom',
'Saline Nasal Douches',
'Lasagna Integrity',
'Startled Worm Cafe',
'Unstoppable Burger Hole',
'Social Media Bucks ',
'Level 6 Reuben',
'Nature’s Bidet',
'The Pancake Spectrum',
'Babadook Penguin',
'Bakery Air ',
'A Powerful Negative',
'Drink Guy Warning',
'Open-air Meat Markets ',
'Sleazy Dickens',
'The Gountain Moats',
'Unphotogenic Rectangle',
'Established Bald Man',
'Liberated Ovum',
'Yell Hole',
'Ministerial Limousine',
'Violent Suck Hole',
'Stormwater Utility Hole Detector',
'Macaroni beach',
'Slug Damage',
'Positive Seaman Probe',
'Pit Rot',
'Pork Giant',
'Virtual Calculus',
'Baguette Pyramid',
'Head Sharon',
'Plateau of Quality',
'Ambiguous Wikipedia',
'Throat Assembly',
'Possible Bozos',
'Super Admin View',
'Fact Circle',
'Banana News',
'Business services',
'Chicken Fingers',
'The Pixel People',
'Hope Probe',
'Chainsaw Disco',
'BONE ISLAND ',
'MASTER PROMOTER',
'Mustard Recipient',
'Front Porch Internet',
'House Leek',
'Meat Cove Man',
'Destruction Date',
'Wanted Meat',
'Plush Unkar Plutt',
'The Pancake Spectrum',
'Conventional Loaf',
'Inaccessible Islands',
'Important Bird Area',
'17 Inches of Glory ',
'Fudge Factor',
'MELANGE DE LEGUMES',
'Tittynope',
'Worrying Pot Blobs',
'Scutus Brevilicus ',
'Too Tall Bandit',
'Potato of the Day',
'TOWER FAN SMASH',
'Half-assed Hand Turkey',
'STRONGER HUMANS',
'WORM SOUP',
'CREED PONY',
'Whisperfest 2020',
'Salty Neighbour',
'Exchange Unified Messaging',
'Horizon of Events',
'Rancid Yak Butter',
'Fretboard Hacks',
'Elusive Olives',
'Partisan Witch Hunt',
'Hamster Hamper',
'Good Monocle Emoji',
'Fresnel Lens',
'Alpha Karens',
'17 Boomers',
'Unconscious Tower Maiden',
'Aggressive Street lobster',
'Decent Melon',
'Virtual Signalling',
'The Bum Gun',
'Western Toilets',
'Cryogenic Superconducting Magnets',
'Portable Soop',
'Hamburger University',
'Giant Hogweed',
'The Growth in the Loaf',
'Zoom Squares',
'Titular Beans',
]

var mattList = ['Face temperature lizards ',
'What about krang',
'Praised by wolves',
'Solar opposites',
'Spanked by the Pope',
'Jet Raider ',
'Cold elbows',
'Immediate Brass - Ladies Get It',
'Humping an ice turtle ',
'Regular Circles of Mules',
'Everyday Champ ',
'Two dads',
'Rage piss',
'The cult called America ',
'Courtesy of Eddie ',
'Munter/Gatherer. ',
'Yam Harvest ',
'The Nocturnal Foreheads',
'Turd Party ',
'The Dog Might Be Fred',
'Phush - jam band that covers the natures best cd',
'Horse riding with Putin',
'According to Brendan',
'Cape Breton Boys ',
'Fux',
'Sweeney Features',
'Khakis at Midnight',
'Mercury in retrograde',
'One Horse Pony',
'Girls in plaid who like dudes',
'Boys pants',
'Maybe I\'\m Greek',
'(Like a) Handful of heart attack',
'Degenerate Operators',
'The Monte Carlo Methods',
'Bloody Ace',
'The Coyote Door',
'The Harvey/Roulston Divide',
'Gut Bugs',
'Them Boomers',
'International Gossip ',
'Two Corollas',
'Cohort of Bogans ',
'Appreciating the Magrittes ',
'Two Dorks and a Big Machine ',
'White Kitten ',
'Skullproot ',
'Larry Saw an Owl',
'All I Ever Saw Were Bats',
'Minas and His Mechanical Hand',
'Dewey Ska',
'Cloud Barn Vibes',
'Dr Steven Wrong and the Clown Grannies',
'Alec Bald Twins ',
'Biscuit Birdhouse',
'80s Bone Dealer ',
'Worst Aid Kit',
'Frat Guitar ',
'Lumberton ',
'Sausage Partner ',
'Chat Line for Atoms',
'CURVEPOPS',
'(Fingers in) Countless Pies',
'Dollar Mixture ',
'Yaas Quatch',
'Bummerslam',
'Partisan Witch Hunt',
'Alpha Karens',
'Yesterday\'\s Extremes',
'Psycho Sequels',
'Golf cart meth bust',
]

// // The randomizer     
    function newWord() {
        var randomnumber = Math.floor(Math.random() * (words.length));
        document.getElementById('answerGoesHere').innerHTML = words[randomnumber];
    }

    function newWordMatt() {
        var randomnumber = Math.floor(Math.random() * (mattList.length));
        document.getElementById('mattAnswer').innerHTML = mattList[randomnumber];
    }
