
var words = ['Le Sob',
'The Perching Derrière ',
'Oaty Bottom',
'Saline Nasal Douches',
'Lasagna Integrity',
'Startled Worm Cafe',
'Unstoppable Burger Hole',
'Social Media Bucks ',
'Level 6 Reuben',
'Nature’s Bidet',
'The Pancake Spectrum',
'Babadook Penguin',
'Bakery Air ',
'A Powerful Negative',
'Drink Guy Warning',
'Open-air Meat Markets ',
'Sleazy Dickens',
'The Gountain Moats',
'Unphotogenic Rectangle',
'Established Bald Man',
'Liberated Ovum',
'Yell Hole',
'Ministerial Limousine',
'Violent Suck Hole',
'Stormwater Utility Hole Detector',
'Macaroni beach',
'Slug Damage',
'Positive Seaman Probe',
'Pit Rot',
'Pork Giant',
'Virtual Calculus',
'Baguette Pyramid',
'Head Sharon',
'Plateau of Quality',
'Ambiguous Wikipedia',
'Throat Assembly',
'Possible Bozos',
'Super Admin View',
'Fact Circle',
'Banana News',
'Business services',
'Chicken Fingers',
'The Pixel People',
'Hope Probe',
'Chainsaw Disco',
'BONE ISLAND ',
'MASTER PROMOTER',
'Mustard Recipient',
'Front Porch Internet',
'House Leek',
'Meat Cove Man',
'Destruction Date',
'Wanted Meat',
'Plush Unkar Plutt',
'The Pancake Spectrum',
'Conventional Loaf',
'Inaccessible Islands',
'Important Bird Area',
'17 Inches of Glory ',
'Fudge Factor',
'MELANGE DE LEGUMES',
'Tittynope',
'Worrying Pot Blobs',
'Scutus Brevilicus ',
'Too Tall Bandit',
'Potato of the Day',
'TOWER FAN SMASH',
'Half-assed Hand Turkey',
'STRONGER HUMANS',
'WORM SOUP',
'CREED PONY',
'Whisperfest 2020',
'Salty Neighbour',
'Exchange Unified Messaging',
'Horizon of Events',
'Rancid Yak Butter',
'Fretboard Hacks',
'Elusive Olives',
'Partisan Witch Hunt',
'Hamster Hamper',
'Good Monocle Emoji',
'Fresnel Lens',
'Alpha Karens',
'17 Boomers',
'Unconscious Tower Maiden',
'Aggressive Street lobster',
'Decent Melon',
'Virtual Signalling',
'The Bum Gun',
'Western Toilets',
'Cryogenic Superconducting Magnets',
'Portable Soop',
'Hamburger University',
'Giant Hogweed',
'The Growth in the Loaf',
'Zoom Squares',
'Titular Beans',
]

// // The randomizer     
    function newWord() {
        var randomnumber = Math.floor(Math.random() * (words.length));
        document.getElementById('answerGoesHere').innerHTML = words[randomnumber];
    }